apiVersion: batch/v1
kind: CronJob
metadata:
  name: virtuosodb-backup-snapshot
spec:
  schedule: "0 0 * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: eks-access
          containers:
          - name: virtuosodb-backup-pv
            image: bitnami/kubectl         
            command: 
            - /bin/bash
            - -c
            - |      
              current_date=$(date +%Y%m%d%H%M%S)
              cat <<EOF | kubectl apply -f -
              apiVersion: snapshot.storage.k8s.io/v1
              kind: VolumeSnapshot
              metadata:
                name: virtuosodb-volume-snapshot-${current_date}
              spec:
                volumeSnapshotClassName: csi-aws-vsc
                source:
                  persistentVolumeClaimName: virtuosodb-volume-1
              EOF
          restartPolicy: Never